spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: postgres
    password: '@122106jc@'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true